### ISSUE TITLE
are you open to commissions?

### ISSUE THREAD

**Issue by nicolasH** [nickcoutsos/dactyl-deskmount#1]
Dear Mr. Coutsos

Would you be open to a commission? I would be interested in the following
- modifications of the design, 
- set of 3d printed parts 
- a completed keyboard

And if so how much would you charge and long would that take?

The design modification would be so that the thumb cluster would be removed and another one would be created in a different location. 
my current thinking would be for it to be positioned below the index column. 
It would be repositioned to be angled about 95° to 100° from the plate plane, like some kind of italic t, and it would be a 2 rows of 1.5 + 1 unit keys and a 1.5u key at the bottom about 100 degrees from the thumb plane.
Given my uncertainty with regard to the best placement and orientation for the thumb cluster i think the best thing would be If it was attached with a stiff but flexible wire of some kind on mounting points  under  the middle finger column.

please let me know if you would be interested in this commission.

Best regards,

Nicolas

**Comment by nickcoutsos** [comment]
Hi Nicolas,

Thanks for your interest in my project but unfortunately I don't plan to take commissions.

I did put some effort into making the design (somewhat) modular but certain aspects make it difficult to accommodate radically different thumb cluster designs without writing a lot of manual code. If you have interest in attempting it yourself it's not impossible, just tedious.

Good luck, I hope you're able to find the right fit in a keyboard design. If you have any questions I'm happy to share what I know!

**Comment by nicolasH** [comment]
thank you for taking the time to reply.

indeed i tried myself first, but ran in the tediousness of it rather quickly, hence this post.

best regards,

nicolas
